.gitignore, gotrue/.gitignore, gotrue/client.py, tests/test_gotrue.py
Adds `set_auth` method that is already found in `gotrue-js`.
Closes #2
=> add set_auth to gotrue client

.gitignore, gotrue/.gitignore, gotrue/__init__.py, gotrue/lib/constants.py, infra/docker-compose.yml, tests/test_gotrue.py
Right now, it seems like the test are failing partially because `gotrue/lib` has been deleted.
Aimed at resolving #4
=> Reinstate lib and fix build

.github/workflows/ci.yml, .pre-commit-config.yaml, Makefile, gotrue/_async/client.py, gotrue/_sync/client.py, gotrue/types.py, infra/docker-compose.yml, poetry.lock, pyproject.toml, tests/_async/test_api_with_auto_confirm_enabled.py, tests/_async/test_client_with_auto_confirm_disabled.py, tests/_async/test_client_with_auto_confirm_enabled.py, tests/_sync/test_api_with_auto_confirm_enabled.py, tests/_sync/test_client_with_auto_confirm_disabled.py, tests/_sync/test_client_with_auto_confirm_enabled.py
=> feat: add pre-commit hook and action for conventional commit and semantic release

gotrue/exceptions.py
Inherit from Exception instead of from BaseException.
More info: [https://docs.python.org/3/tutorial/errors.html#tut-userexceptions](https://docs.python.org/3/tutorial/errors.html#tut-userexceptions)
Thanks for the report: @ktosiek
=> Inherit from Exception

gotrue/_async/api.py, gotrue/_sync/api.py
The delete user method is not working.
This seems to be due to a leftover from javascript style string formatting (dollar sign).
Proposed edits.
These seem to work in the case of my local development environment.
=> fix: string formatting in `delete_user`

gotrue/_sync/client.py
because the intention is good but instead receives an annoying print.
=> chore: fix http warning use

gotrue/_async/client.py, gotrue/_sync/client.py
Timer takes in seconds and not milliseconds.  Fixes #163 - see #163  for further details
=> fix: adjust timer units and drop * 1000

gotrue/helpers.py
fix proposed @kn
See #246 for details
Thanks kn!
=> fix: patch padding for base64

gotrue/types.py
Bug fix
`supabase.auth.get_user` raises 
```
gotrue.errors.AuthRetryableError: 1 validation error for UserResponse
user -> identities -> 0 -> last_sign_in_at
field required (type=value_error.missing)
```
when the user hasn't signed in before
=> optional last_sign_in_at in UserIdentity type

gotrue/_async/gotrue_client.py, gotrue/_sync/gotrue_client.py
[#246](https://github.com/supabase-community/gotrue-py/issues/246)
urlencode calls quote on params
=> fix issue #246

README.md, pyproject.toml
=> feat: update README, release v1.0.2

.github/workflows/ci.yml, gotrue/types.py
-  With version 7, Semantic release [no longer supports the use of PyPI Token, username and password](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html#removal-of-pypi-token-repository-username-and-repository-password-inputs) We should instead go through the official PyPA action and trusted publisher. The trusted publisher has been configured.
- Separately contains a change which Addresses #292 by adding the types for the new providers.  Let me know if it's preferred that we split this into a separate PR
=> fix: fix semantic release

pyproject.toml
Looks like the [version.toml](https://python-semantic-release.readthedocs.io/en/latest/migrating_from_v7.html#version-toml) needs to be updated too
=> fix: update version options

gotrue/_async/gotrue_admin_api.py, gotrue/_sync/gotrue_admin_api.py
feature
The auth admin `list_users` function will only return the 50 most recent users without the option to fetch more per page or move to another page
Now, the auth admin `list_users` function accepts both `page` and `per_page` named parameters to enable pagination.
None
=> feat: support pagination for auth admin list_users

gotrue/types.py
* Allows passing a `token_hash` and `type` in `verify_otp` method 
* Supports this change on gotrue: https://github.com/supabase/gotrue/pull/1165
This is the equivalent of https://github.com/supabase/gotrue-js/pull/722 to make it easier to do fully server-side when double confirm is turned on for email confirmation.
=> fix: add verify token hash

gotrue/helpers.py
Bug fix
When set_session() is called with a base64URL encoded JWT (instead of normal base64 encoding), it fails. Giving it a normally encoded JWT also fails, because the request later uses the access_token as passed here and it requires base64URL encoding.
By using urlsafe_b64decode, base64URL encoded JWTs now work properly
none
=> Use urlsafe_b64decode to properly handle URL-encoded JWTs

gotrue/_async/gotrue_client.py
It fixes on_auth_state_change not be async. Somehow it got reverted on a refactor (https://github.com/supabase-community/gotrue-py/commit/e7ebc64112d970673265c7b314a1e8820fc0f7e1)
It was async.
It's not async anymore.
This causes problems when using the supabase client, since it's not being awaited: https://github.com/supabase-community/supabase-py/blob/main/supabase/_async/client.py#L90
=> fix: remove unnecessary async to on_auth_state_change

gotrue/types.py
Bug fix
When I run tests I see the following warnings:
```
(venv) ... % pytest src/tests/integration/test_abc.py       
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.9.13, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/...
configfile: pytest.ini
plugins: anyio-4.1.0
collected 7 items                                                                                                                                                                                          
src/tests/integration/test_abc.py ....... …
```
=> bug fix: use pydantic v2 model.model_rebuild

gotrue/_async/gotrue_admin_api.py, gotrue/_async/gotrue_client.py, gotrue/_sync/gotrue_admin_api.py, gotrue/_sync/gotrue_client.py, gotrue/types.py
Adds the scope option to the `sign_out` method which can be used to control which sessions should be signed out of the account.
Closes #371 
Only supports global scope
Supports `global`, `local` and `others` scope.
https://github.com/supabase/gotrue/pull/1112
https://github.com/supabase/gotrue-js/pull/713
=> feat: add sign_out() scope option

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml
Bug fix, feature, docs update, ...
=> update ci to include python 3.12 in tests

supabase_auth/_sync/api.py, supabase_auth/helpers.py
- Tiny fixes and proper code style.
=> Fixes and style

supabase_auth/_async/gotrue_base_api.py, supabase_auth/_sync/api.py, supabase_auth/_sync/gotrue_base_api.py
- Add `follow_redirects=True`.
- All other Supabase libs follow redirects by default.
=> Follow redirects

infra/docker-compose.yml, supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Fixes #504.
Follows https://github.com/supabase/auth-js/blob/f131300d753634fcf3fbc93dc7a762031f096749/src/GoTrueClient.ts#L370-401
With new types as well
Feedback welcomed.
=> add anonymous login

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Add missing feature
When using phone auth you can only use `sms` as a channel
When using phone auth you can now use `sms` or `whatsapp` as a channel
=> add channel to sign_in and sign_up options

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
Bug fix
Currently the `should_create_user` property is incorrectly named inside the `sign_in_with_otp` method
The `should_create_user` property is correctly named inside the `sign_in_with_otp` method
=> update property name for should_create_user

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Add the `sign_in_with_id_token` method for Google and others one tap integration.
There is no `sign_in_with_id_token` method
There is now a `sign_in_with_id_token` method
=> add sign_in_with_id_token method

supabase_auth/types.py
Bug fix
Currently the returned user model doesn't show the `is_anonymous` type
The returned user model shows the `is_anonymous` type
=> add is_anonymous type to the user model

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
- MFA Phone.
- See https://github.com/supabase/auth-js/pull/932/files
=> feat: add MFA Phone

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Update method name to match the JS client library.
=> fix: update password reset method name to match js lib

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
feature
There is no reauthenticate method
Added reauthenticate method
=> feat: add reauthenticate method

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Add resend method for emails to be resent for an existing signup confirmation email, email change email, SMS OTP or phone change OTP.
=> feat: add resend method

supabase_auth/_async/gotrue_admin_api.py, supabase_auth/_sync/gotrue_admin_api.py, supabase_auth/types.py
I made a change in a previous PR to fix the Options type https://github.com/supabase/auth-py/pull/584, but didn't realise it was being used by the `invite_user_by_email` options type.
=> fix: update invite user by email option type

supabase_auth/_async/gotrue_admin_api.py, supabase_auth/_async/gotrue_base_api.py, supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/api.py, supabase_auth/_sync/client.py, supabase_auth/_sync/gotrue_admin_api.py, supabase_auth/_sync/gotrue_base_api.py, supabase_auth/_sync/gotrue_client.py
=> feat: Proxy support

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
Bug fix
Requires channel property
Does not require the channel property
https://github.com/supabase/supabase-py/issues/921
=> fix: mfa challenge channel field not required

supabase_auth/_sync/client.py, supabase_auth/helpers.py
- Check if `url` arg is an HTTP URL.
=> feat: Check if url is an HTTP URL

supabase_auth/_sync/client.py, supabase_auth/helpers.py
- Check if `token` arg is a JWT string.
- Based (but not copied) from https://github.com/supabase/supabase-js/blob/6193a967a8d07605889446e9eabab149a275ee54/src/lib/helpers.ts#L75
=> feat: Check if token is a JWT

supabase_auth/timer.py
Bug fix
If any sign in method is called a timer kicks off to handle token refresh, however if you should exit the program the timer gets disrupted and doesn't stop correctly because of the thread its running on.
Timer stops correctly because it now makes use of a daemon thread.
https://github.com/supabase/supabase-py/issues/494
https://github.com/supabase/supabase-py/issues/844
https://github.com/supabase/supabase-py/issues/451
=> fix: set timer to be use daemon thread

.github/workflows/ci.yml, supabase_auth/_async/gotrue_client.py, tests/_async/test_gotrue_admin_api.py, tests/_sync/test_gotrue_admin_api.py, tests/test_helpers.py
- Add more unittests. Increase Coverage.
=> chore(tests): Increase coverage

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
Bug fix
`httpx` requests fail if the url includes the query params, this was working in version `0.27.2` of httpx.
The library no uses query params for all `httpx` requests
=> fix: use query params for all httpx requests

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
Bug fix
If an exception is raised during sign_out the session isn't cleared from the storage even though user is signed out
If an exception is raised during sign_out the session is cleared from the storage
=> fix: sign_out not clearing session when exception raised

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py
Bug fix - Corrects the handling of `redirect_to` parameter in SSO authentication.
Closes #670
In the GoTrue client's `sign_in_with_sso` method, the `redirect_to` parameter is being passed as a separate parameter to the `_request` method instead of being included in the request body. This can cause issues with SSO redirects not working as expected.
Current implementation:
```python
return self._request(
"POST",
"sso",
body={
"domain": domain,
"skip_http_redirect": skip_http_redirect,
"gotrue_meta_security": {
"captcha_token": "",
},
},
redirect_to=redirect_to,  # Incorrectly placed here
xform=parse_sso_response,
)
```
Relates to issue: [#670](https://github.com/supabase/auth-py/issues/670)
The redirect_to parameter is now correctly included in the request body:
```python
return …
```
=> fix: move redirect_to into metadata for SSO authentication

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py, tests/_async/test_gotrue.py, tests/_sync/test_gotrue.py
fix https://github.com/supabase/auth-py/issues/684
=> fix: enroll mfa totp

tests/_async/test_gotrue.py, tests/_sync/test_gotrue.py, tests/test_helpers.py
Adds test coverage for
AsyncClient
- initialize_from_url
- exchange_code_for_session
- get_authenticator_assurance_level
- link_identity
- get_user_identities
- unlink_identity
- verify_otp
- sign_in_with_password
- test_sign_in_with_otp
- test_sign_out
helpers
- model_dump
- model_dump_json
- parse_<xxx>_response
- is_valid_jwt
- validate_exp
Which raise the coverage level to 88%
Please do review the tests and make sure they're testing behavior appropriately. About ~50% was LLM generated
=> Increase test coverage to 88%

README.md
Fix coverage badge and update README
=> chore: update README and fix coverage badge

supabase_auth/_async/gotrue_admin_api.py, supabase_auth/_sync/gotrue_admin_api.py, supabase_auth/helpers.py, tests/_async/test_gotrue_admin_api.py, tests/_sync/test_gotrue_admin_api.py
This pull request introduces UUID validation for user-related operations in both the asynchronous and synchronous versions of the `gotrue_admin_api` module. It ensures that invalid UUIDs are caught early, preventing unnecessary API calls. Additionally, new tests have been added to verify this behavior.
* Added a new helper function `is_valid_uuid` in `supabase_auth/helpers.py` to validate UUIDs.
* Introduced a `_validate_uuid` method in both `supabase_auth/_async/gotrue_admin_api.py` and `supabase_auth/_sync/gotrue_admin_api.py` to validate UUIDs before making API requests. [[1]](diffhunk://#diff-fc39cc968a0c0a1c8048ea263364bddcdab0f8bb2efe29ce99e6f6a4e801f640R192-R202) [[2]](diffhunk://#diff-95a69ea357efbbd4306ec7fea3f233c4703da9c11182d33faf79a35df21c384dR192-R202)
* Updated all relevant …
=> fix: validate uuid on admin methods and fix wrong factor in delete_factor method

supabase_auth/_async/gotrue_client.py, supabase_auth/_sync/gotrue_client.py, supabase_auth/types.py
Bug fix
`.update_user` method is missing the `email_redirect_to` property.
`.update_user` method now has the `email_redirect_to` property.
I will add a PR to update the reference docs on the Supabase website in relation to this too.
In relation to #727
=> fix: add missing email_redirect_to option
