gotrue/_async/api.py
gotrue/_sync/api.py
tests/_async/test_api_with_auto_confirm_enabled.py
tests/_sync/test_api_with_auto_confirm_enabled.py

fix: delete_user returns Exception event if response is Ok

---

gotrue/_async/api.py
gotrue/_async/client.py
gotrue/_sync/api.py
gotrue/_sync/client.py

ref: https://github.com/supabase/gotrue/pull/318

feat: add create user param to sign in

---

gotrue/__init__.py
pyproject.toml

feat: bump to 1.0.0

---

gotrue/__init__.py
pyproject.toml

feat: bump version to 1.0.1

---

gotrue/__init__.py

fix: bump __init__ version to 1.02

---

.github/workflows/ci.yml
gotrue/__init__.py
pyproject.toml

feat: release v1.0.3

---

.github/workflows/ci.yml
gotrue/_async/api.py
gotrue/_async/client.py
gotrue/_async/gotrue_admin_api.py
gotrue/_async/gotrue_base_api.py
gotrue/_async/gotrue_client.py
gotrue/_sync/api.py
gotrue/_sync/client.py
gotrue/_sync/gotrue_admin_api.py
gotrue/_sync/gotrue_base_api.py
gotrue/_sync/gotrue_client.py
gotrue/helpers.py
gotrue/types.py
pyproject.toml

Re-adds support for pydantic v1 via a few compatibility functions in `helpers.py`
The change is mostly mechanical and mirrors the update that transitioned from pydantic  v1 to v2 https://github.com/supabase-community/gotrue-py/pull/286
---
resolves #291
ref https://github.com/supabase-community/supabase-py/issues/517

Support for pydantic v1 & v2

---

.github/workflows/ci.yml

Add contents permission to allow GH bot to upload

chore: add contents permission

---

.pre-commit-config.yaml
pyproject.toml

Changes to the semantic release variables
Version in the library isn't getting updated when a release happens
Version is now getting updated when a release happens

Add correct variables for semantic release

---

poetry.lock
pyproject.toml

fix: add latest semantic-release dependency

---

gotrue/_async/gotrue_admin_api.py
gotrue/_sync/api.py
gotrue/_sync/gotrue_admin_api.py

Feature.
No support for soft deletion.
Optionally request soft deletion.
Issue: https://github.com/supabase-community/gotrue-py/issues/375

add soft delete support to "delete user"

---

tests/_async/test_gotrue_admin_api.py
tests/_sync/test_gotrue_admin_api.py

Test and correspondingly build are failing due to a change in error message returned by Supabase Auth

fix: fix build by updating error message in test

---

gotrue/_async/gotrue_client.py
gotrue/_sync/gotrue_client.py
gotrue/types.py
infra/docker-compose.yml

We add the newly introduced identity linking methods from LWX.

feat: add new identity linking methods release in LWX

---

.github/workflows/manual_pypi_publish.yml

Bug fix, feature, docs update, ...

chore: bump fixed version of poetry

---

supabase_auth/_async/gotrue_client.py
supabase_auth/_sync/gotrue_client.py
supabase_auth/helpers.py
supabase_auth/types.py

Bug fix
Link identity methods don't work
Link identity methods now work

fix all link identity methods

---

supabase_auth/_async/gotrue_client.py

Bug fix.
Doesn't have `await` keyword
Add missing `await` keyword

add await to async call for anonymous sign in request

---

.github/workflows/ci.yml

Release pipeline fix
Release pipeline is currently broken
This PR should fix the release pipeline.

fix: update ci pipeline

---

.github/workflows/ci.yml

ci: remove PAT

---

.github/workflows/ci.yml
.github/workflows/manual_pypi_publish.yml

Update manual PyPi ci workflow

ci: update manual publish to pypi workflow

---

supabase_auth/errors.py

Bug fix: add additional error codes

fix: add email_address_invalid error code

---

.coveragerc

- Ignore deprecated unused file, increase coverage to 75%
- Can be removed on next release.

chore(tests): ignore deprecated unused file

---

.github/workflows/ci.yml
.github/workflows/conventional-commits.yml
.github/workflows/manual_pypi_publish.yml
.github/workflows/stale.yml

some small changes to actions, namely explicit permissions

ci: explicit permissions for actions
